framework:
    validation:
        auto_mapping:
        # Enables validator auto-mapping support.
        # For instance, basic validation constraints will be inferred from Doctrine's metadata.
        #auto_mapping:
            # an empty array means that all entities that belong to that
            # namespace will add automatic validation
#            App\Entity\: []
#            'Foo\': ['Foo\Some\Entity', 'Foo\Another\Entity']
when@test:
    framework:
        validation:
            not_compromised_password: false
